service: ecommerce-checkout-rewards

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    POSTGRES_USER: ${env:POSTGRES_USER, 'root'}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD, 'pass@123'}
    POSTGRES_DB: ${env:POSTGRES_DB, 'ecommerce'}
    JWT_SECRET: ${env:JWT_SECRET, 'supersecret'}

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
        - x-idempotency-key
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS

functions:
  checkout:
    handler: src/handlers/checkout/checkout.handler
    events:
      - httpApi:
          path: /carts/{cartId}/checkout
          method: post
  getProducts:
    handler: src/handlers/products/getProducts.handler
    events:
      - httpApi:
          path: /products
          method: get
  getOrCreateCart:
    handler: src/handlers/carts/carts.getOrCreateCart
    events:
      - httpApi:
          path: /carts
          method: post
  getCart:
    handler: src/handlers/carts/carts.getCart
    events:
      - httpApi:
          path: /carts/{cartId}
          method: get
  addCartItem:
    handler: src/handlers/carts/carts.addCartItem
    events:
      - httpApi:
          path: /carts/{cartId}/items
          method: post
  updateCartItem:
    handler: src/handlers/carts/carts.updateCartItem
    events:
      - httpApi:
          path: /carts/{cartId}/items/{productId}
          method: patch
  removeCartItem:
    handler: src/handlers/carts/carts.removeCartItem
    events:
      - httpApi:
          path: /carts/{cartId}/items/{productId}
          method: delete
  generateCoupon:
    handler: src/handlers/admin/admin.generateCoupon
    events:
      - httpApi:
          path: /admin/coupons/generate
          method: post
  adminReport:
    handler: src/handlers/admin/admin.getReport
    events:
      - httpApi:
          path: /admin/report
          method: get
  getRewards:
    handler: src/handlers/rewards/rewards.getRewards
    events:
      - httpApi:
          path: /me/rewards
          method: get
  getCoupons:
    handler: src/handlers/rewards/rewards.getCoupons
    events:
      - httpApi:
          path: /me/coupons
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
